"""Write the vault's machine zones. Nothing else in the vault is touched.

    tcg/mtg/_generated/<deck>-data.md    regenerated every sync; stale ones removed
    tcg/mtg/_generated/collection-summary.md
    tcg/mtg/_log/prices.md               append-only, one snapshot per day
    tcg/mtg/_log/<deck>-versions.md      append-only, only when a list changes

Authored notes pull generated ones in with ![[aesi-lands-data]]. No dots in
generated names: Obsidian reads "aesi-lands.data" as a ".data" file.
"""

import hashlib
import json
from collections import Counter
from datetime import date
from pathlib import Path

from mtg.analysis.ownership import BUY, MARK, OWN, Row, summary
from mtg.analysis.pricing import DeckPrice
from mtg.config import data_dir
from mtg.models import Deck, Holding
from mtg.store import Catalog


def _money(x: float | None) -> str:
    return f"${x:,.2f}" if x is not None else "—"


def _tix(x: float | None) -> str:
    return f"{x:,.2f}" if x is not None else "—"


def _write(path: Path, text: str) -> bool:
    """Write only if different, so pCloud doesn't resync unchanged files."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True


def deck_data(deck: Deck, rows: list[Row], dp: DeckPrice, unresolved: list[str], today: str,
              imports: dict[str, str] | None = None) -> str:
    s = summary(rows)
    buy = [(r, l) for r, l in zip(rows, dp.lines) if r.status == BUY]
    out = [
        "---",
        f"title: {deck.slug}-data",
        "type: generated",
        f"deck: {deck.slug}",
        f"generated: {today}",
        "---",
        "",
        "> [!warning] Generated by `mtg sync` — edits here are overwritten",
        "",
        f"**{deck.count()} cards** · {MARK[OWN]} {s[OWN]} own · {MARK[BUY]} {s[BUY]} buy",
        "",
        "| | Paper | MTGO |",
        "|---|---|---|",
        f"| Whole deck | {_money(dp.usd_total)} | {_tix(dp.tix_total)} tix |",
        f"| Still to buy | {_money(dp.usd_to_buy)} | — |",
        "",
    ]
    if buy:
        out += ["## Buy", "", "| Buy | Card | Paper | MTGO |", "|---|---|---|---|"]
        for r, l in sorted(buy, key=lambda x: -(x[1].usd or 0)):
            note = f" (own {r.owned} of {r.needed})" if r.partial else ""
            out.append(f"| {MARK[BUY]} {r.shortfall} | [[{r.name}]]{note} | {_money(l.usd)} | {_tix(l.tix)} |")
        out.append("")
    if dp.missing_on_mtgo:
        out += ["## Not on MTGO", "", ", ".join(f"[[{n}]]" for n in dp.missing_on_mtgo), ""]
    if unresolved:
        out += ["> [!bug] Names that didn't match any card", "> " + ", ".join(unresolved), ""]
    for title, text in (imports or {}).items():
        out += [f"## {title}", "", "```", text.rstrip(), "```", ""]
    return "\n".join(out)


def collection_summary(holdings: list[Holding], catalog: Catalog, today: str) -> str:
    counted = [h for h in holdings if h.source == "manabox" and h.oracle_id]
    total = sum(h.quantity for h in counted)
    unique = len({h.oracle_id for h in counted})
    valued = []
    for h in counted:
        usd = catalog.printing_usd(h.scryfall_id) if h.scryfall_id else None
        if usd is None:
            usd = catalog.prices(h.oracle_id).usd
        valued.append((usd or 0) * h.quantity)
    top = sorted(zip(valued, counted), key=lambda x: -x[0])[:15]
    precons = Counter(h.source for h in holdings if h.source.startswith("precon:"))  # noqa: F841
    lines = [
        "---", "title: collection-summary", "type: generated", f"generated: {today}", "---", "",
        "> [!warning] Generated by `mtg sync` — edits here are overwritten", "",
        f"**{total:,} cards · {unique:,} unique · ~{_money(sum(valued))}** (ManaBox export)", "",
    ]
    if precons:
        lines += ["Sealed precons counted as owned: " + ", ".join(p.split(":", 1)[1] for p in precons), ""]
    lines += ["## Most valuable", "", "| Card | Copies | Value |", "|---|---|---|"]
    lines += [f"| [[{catalog.name(h.oracle_id)}]] | {h.quantity} | {_money(v)} |" for v, h in top]
    return "\n".join(lines) + "\n"


def append_prices(log: Path, cards: list[tuple[str, float | None, float | None]], today: str) -> int:
    log.parent.mkdir(parents=True, exist_ok=True)
    if not log.exists():
        log.write_text(
            "---\ntitle: prices\ntype: log\n---\n\n# Price log\n\n"
            "Appended by `mtg sync` for every unticked #mtg/buy card. Never edit.\n\n"
            "`date | card | paper | tix`\n\n", encoding="utf-8")
    existing = log.read_text(encoding="utf-8")
    if f"\n{today} | " in existing:
        return 0
    with log.open("a", encoding="utf-8") as f:
        for name, usd, tix in sorted(cards):
            f.write(f"{today} | {name} | {_money(usd)} | {_tix(tix)}\n")
    return len(cards)


def _state_path() -> Path:
    return data_dir() / "sync-state.json"


def append_version(log_dir: Path, deck: Deck, catalog: Catalog, today: str) -> bool:
    """Append a +/- diff when a deck's list changed since the last sync."""
    legacy = log_dir / f"{deck.slug}.versions.md"
    if legacy.exists() and not (log_dir / f"{deck.slug}-versions.md").exists():
        legacy.rename(log_dir / f"{deck.slug}-versions.md")
    cards = Counter()
    for e in deck.entries:
        cards[catalog.name(e.oracle_id) if e.oracle_id else e.name] += e.quantity
    digest = hashlib.sha256(json.dumps(sorted(cards.items())).encode()).hexdigest()[:16]
    state = json.loads(_state_path().read_text()) if _state_path().exists() else {}
    prev = state.get(deck.slug)
    if prev and prev["hash"] == digest:
        return False
    log = log_dir / f"{deck.slug}-versions.md"
    log_dir.mkdir(parents=True, exist_ok=True)
    if not log.exists():
        log.write_text(f"---\ntitle: {deck.slug}-versions\ntype: log\ndeck: {deck.slug}\n---\n\n"
                       "Appended by `mtg sync` when the list changes. Never edit.\n", encoding="utf-8")
    with log.open("a", encoding="utf-8") as f:
        if prev is None:
            f.write(f"\n## {today}\n\nBaseline: {sum(cards.values())} cards.\n")
        else:
            old = Counter(prev["cards"])
            added, removed = cards - old, old - cards
            f.write(f"\n## {today}\n\n")
            f.writelines(f"- \\+ {n} [[{c}]]\n" for c, n in sorted(added.items()))
            f.writelines(f"- \\- {n} [[{c}]]\n" for c, n in sorted(removed.items()))
    state[deck.slug] = {"hash": digest, "cards": dict(cards)}
    _state_path().parent.mkdir(parents=True, exist_ok=True)
    _state_path().write_text(json.dumps(state, indent=1))
    return True


def write_deck(gen_dir: Path, deck: Deck, text: str) -> bool:
    return _write(gen_dir / f"{deck.slug}-data.md", text)


def prune(gen_dir: Path, keep: set[str]) -> list[str]:
    """_generated/ is repo-owned: remove notes this sync didn't produce."""
    removed = []
    for p in gen_dir.glob("*.md"):
        if p.name not in keep and p.name != "README.md":
            p.unlink()
            removed.append(p.name)
    return removed


def write_summary(gen_dir: Path, text: str) -> bool:
    return _write(gen_dir / "collection-summary.md", text)


def today() -> str:
    return date.today().isoformat()
